nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: ['*']
        max_age: 3600
        allow_credentials: false

    paths:
        '^/': ~
