services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        APP_ENV: dev
    volumes:
      - ./:/app
    restart: unless-stopped
    container_name: tunduk-gateway-app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/app
      - ./.docker/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    container_name: tunduk-gateway-nginx